### ISSUE TITLE
please upgrade npm version!

### ISSUE THREAD

**Issue by reaby** [node-gfx/node-canvas-prebuilt#58]
github has latest version of  2.0.1 while npm still 2.0.alpha.14

**Comment by chearon** [comment]
Actually you can just `npm install canvas@2.0.1` and it downloads prebuilds from here! I won't be publishing `canvas-prebuilt@2.x` since I don't think there's a reason to anymore.

**Comment by reaby** [comment]
many thanks

**Comment by delucis** [comment]
@chearon What exactly is the reasoning behind not publishing to npm?

Right now `npm i canvas-prebuilt` will install `2.0.0-alpha.14`. In general people running `npm install` expect to install the latest version, or at least a non-alpha version. If this is just waiting on #57, then I totally understand, but not publishing to npm at all seems likely to cause problems for users who don’t realise they’re not getting the latest version.

**Comment by gyfis** [comment]
@chearon I totally understand the reasoning behind not publishing canvas-prebuilt anymore, however, if you could publish one last stable version, e.g. 2.0.0 or 2.0.1, with `librsvg` support, that would be super helpful for us that need to have `node-canvas@1.6.x` installed because of fabric (and thus cannot install node-canvas@2.x as well).

**Comment by chearon** [comment]
Yes, absolutely, see #59 and #42. Sorry, I've been busy and this is not super fun to maintain :( but I'll have time this weekend to do it!
