### ISSUE TITLE
Prebuilt for node_v72

### ISSUE THREAD

**Issue by BenoitClaveau** [node-gfx/node-canvas-prebuilt#78]
Could you please create a prebuilt for window node_v72.

**Comment by papandreou** [comment]
@chearon, sorry to ping you, but do you know why those `win32` prebuilts aren't in [the 2.6.0 release](https://github.com/node-gfx/node-canvas-prebuilt/releases/tag/v2.6.0)? Looks like you managed to include them in [2.5.0](https://github.com/node-gfx/node-canvas-prebuilt/releases/tag/v2.5.0), except for the node 12/v72 one?

Would be great to have a canvas release with prebuilts supporting both win32 and node 12 :sweat_smile:

I don't have access to a Windows machine, but do let me know if there's anything else I can do to help :)

**Comment by chearon** [comment]
@papandreou no worries at all, I needed the extra push. Binaries for 2.6.0/Windows/all node versions are up, as well as 2.5.0/Windows/Node 12!

2.5.0: was an issue with the wrong NAN version.

2.6.0: AppVeyor must have updated their images because it immediately built and pushed the new binaries when I started testing various fixes to MSYS2.

Sorry for the long wait everyone. At least I have some good ideas in case MSYS2 breaks like this again.

**Comment by LinusU** [comment]
@chearon awesome 👏 👏  tagging `latest` to 2.6.0 now 🚀
